### ISSUE TITLE
cant mine for the mainchain node?

### ISSUE THREAD

**Issue by formatme** [opoll/opollminer#45]
```
Node type (shard/mainchain): mainchain
there was an error starting your mainchain node.
TypeError: Cannot read property 'initialize' of undefined
    at startNode (C:\Users\formatme\opollminer\lib\runner.js:38:21)
    at rl.question (C:\Users\formatme\opollminer\lib\runner.js:75:5)
    at Interface._onLine (readline.js:280:5)
    at Interface._line (readline.js:631:8)
    at Interface._ttyWrite (readline.js:911:14)
    at ReadStream.onkeypress (readline.js:160:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opollminer@0.1.0 start: `node lib/runner`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opollminer@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\formatme\AppData\Roaming\npm-cache\_logs\2018-04-01T08_54_37_769Z-debug.log
```

**Comment by formatme** [comment]
checked out the dev branch
getting this now

Node type (shard/mainchain): (node:23200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1: The filename, directory name, or volume label syntax is incorrect.

(node:23200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): OpenError: IO error: ./db/: The filename, directory name, or volume label syntax is incorrect.

(node:23200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): OpenError: IO error: ./db/: The filename, directory name, or volume label syntax is incorrect.

(node:23200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): OpenError: IO error: ./db/: The filename, directory name, or volume label syntax is incorrect.

(node:23200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): OpenError: IO error: ./db/: The filename, directory name, or volume label syntax is incorrect.

(node:23200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): OpenError: IO error: ./db/: The filename, directory name, or volume label syntax is incorrect.

**Comment by formatme** [comment]
checked out the dev branch. shard isn't working as well 

```
Node type (shard/mainchain): mmainchain

Node type (shard/mainchain): mainchain
there was an error starting your mainchain node.
TypeError: Cannot read property 'initialize' of undefined
    at startNode (C:\Users\formatme\opollminer-dev\lib\runner.js:41:21)
    at rl.question (C:\Users\formatme\opollminer-dev\lib\runner.js:78:5)
    at Interface._onLine (readline.js:280:5)
    at Interface._line (readline.js:631:8)
    at Interface._ttyWrite (readline.js:911:14)
    at ReadStream.onkeypress (readline.js:160:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opollminer@0.1.0 start: `node lib/runner`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opollminer@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\formatme\AppData\Roaming\npm-cache\_logs\2018-04-01T09_08_46_488Z-debug.log
C:\Users\formatme\opollminer-dev>npm install
up to date in 1.38s

C:\Users\formatme\opollminer-dev>npm start

> opollminer@0.1.0 start C:\Users\formatme\opollminer-dev
> node lib/runner

unable to load configuration; no configuration file found
Node type (shard/mainchain): shard
initializing shard logic controller
removing all inactive shards from worker queue
[NET] Configuring shard P2P routes
[NET] Listening on port 9011 in development mode
Command line initialized. Type help to view a list of commands.
AdminAuthToken: xxxxx
(node:30876) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 404
(node:30876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zack-w** [comment]
not implemented
